import { describe, expect, test } from "bun:test";
import * as app from "hazumi/app";
import * as assets from "hazumi/assets";
import * as debug from "hazumi/debug";
import * as draw from "hazumi/draw";
import * as input from "hazumi/input";
import * as physicsPlugin from "hazumi/physics";
import * as particlesApi from "hazumi/particles";
import * as scene from "hazumi/scene";

describe("capability subpath exports", () => {
  test("ship their runtime values", () => {
    expect(typeof app.start).toBe("function");
    expect(typeof assets.loadImage).toBe("function");
    expect(typeof assets.loadText).toBe("function");
    expect(typeof assets.loadJson).toBe("function");
    expect(typeof assets.loadFont).toBe("function");
    expect(typeof assets.AssetLoadError).toBe("function");
    expect(typeof assets.fromAseprite).toBe("function");
    expect(typeof assets.fromTiled).toBe("function");
    expect(typeof assets.spritesheet).toBe("function");
    expect(typeof draw.circle).toBe("function");
    expect(typeof draw.tint).toBe("function");
    expect(typeof draw.noTint).toBe("function");
    expect(typeof assets.sliceFrame).toBe("function");
    expect(typeof draw.scoped).toBe("function");
    expect(typeof draw.measureText).toBe("function");
    expect(typeof draw.textWidth).toBe("function");
    expect(typeof draw.wrapText).toBe("function");
    expect(typeof draw.NoActiveSceneError).toBe("function");
    expect(typeof input.keyIsDown).toBe("function");
    expect(typeof input.input).toBe("object");
    expect(typeof scene.screen).toBe("object");
    expect(typeof scene.time).toBe("object");
    expect(typeof scene.camera).toBe("object");
    expect(typeof scene.random).toBe("object");
    expect(typeof scene.tween).toBe("function");
    expect(typeof scene.sequence).toBe("function");
    expect(typeof physicsPlugin.physics).toBe("function");
    expect(typeof physicsPlugin.Shape).toBe("object");
    expect(typeof debug.overlay).toBe("function");
    expect(typeof particlesApi.particles).toBe("function");
    expect(typeof draw.fillRgba).toBe("function");
    expect(typeof draw.tintRgba).toBe("function");
  });
});
